### ISSUE TITLE
MJD range for asteroids not working

### ISSUE THREAD

**Issue by nicolas-erasmus** [lukeshingles/atlasserver#19] opened 2021-10-14 20:33 UTC
It looks like when entering a MJD range when extracting asteroid forced photometry that the range is being ignored.

I tried:
RA Dec / MPC names: mpc 2010 OE117
MJD min: 59439
MJD max: 59443

And the result was photometry (and available stamps) from ~57400 to  ~59400 i.e. the entire available dataset MJD range.

I tried using both reduced and difference images with he same result.

**Comment by lukeshingles** [comment] 2021-10-15 10:25
This issue was caused by a space in the MPC name, which I didn't handle correctly. Please discard those old results (perhaps after checking against new request), because they might be for completely the wrong set of coordinates. If the issue is fixed now, please close it, or otherwise let me know.

**Closed as completed** 2021-10-18 13:51 UTC
